"""Optional AI layer (spec 28-29).

Two rules the implementation enforces mechanically rather than by prompt alone:

1. The model only ever sees evidence that exists in the database.
2. Every claim it returns must cite an ``evidence_id`` present in that context. Claims
   citing anything else are **dropped**, not repaired — the model cannot invent an
   identity, relationship, source, or piece of evidence into the record.
"""

from __future__ import annotations

import json
import re
import uuid
from dataclasses import dataclass
from typing import Any

import httpx
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import get_settings
from app.models import Entity, IdentityCandidate, Observation, Relationship

DISCLAIMER = (
    "Generated by a language model from stored evidence only. Every statement is bound to "
    "an observation id; treat it as a reading aid, not as a finding."
)

SYSTEM_PROMPT = """You are an OSINT analysis assistant working inside an evidence-first platform.

Hard rules:
- Use ONLY the evidence provided. Never introduce a name, account, relationship or source
  that is not in it.
- Never assert that two accounts belong to the same person. Say what the evidence supports
  and give a confidence.
- Every claim must cite at least one evidence_id from the context.

Reply with JSON only, in this exact shape:
{"summary": "<= 6 sentences",
 "claims": [{"statement": "...", "evidence_ids": ["<id from context>"], "confidence": 0.0}]}"""


class AIDisabled(RuntimeError):
    pass


@dataclass
class AIClaim:
    statement: str
    evidence_ids: list[uuid.UUID]
    confidence: float


class AIService:
    def __init__(self, session: AsyncSession) -> None:
        self.session = session
        self.settings = get_settings()

    @property
    def enabled(self) -> bool:
        return self.settings.ai_enabled and self.settings.llm_provider != "none"

    async def status(self) -> dict[str, Any]:
        if not self.enabled:
            return {
                "enabled": False,
                "provider": self.settings.llm_provider,
                "model": self.settings.llm_model,
                "reachable": False,
                "detail": "AI layer is disabled (AI_ENABLED=false)",
            }
        reachable, detail = await self._ping()
        return {
            "enabled": True,
            "provider": self.settings.llm_provider,
            "model": self.settings.llm_model,
            "reachable": reachable,
            "detail": detail,
        }

    async def _ping(self) -> tuple[bool, str]:
        try:
            async with httpx.AsyncClient(timeout=5.0) as client:
                response = await client.get(f"{self.settings.llm_base_url.rstrip('/')}/api/tags")
            if response.status_code == 200:
                models = [m.get("name", "") for m in response.json().get("models", [])]
                return True, f"{len(models)} local model(s) available"
            return False, f"LLM host returned HTTP {response.status_code}"
        except Exception as exc:
            return False, f"cannot reach {self.settings.llm_base_url}: {type(exc).__name__}"

    # -- grounded summarisation ------------------------------------------------

    async def summarize(
        self, investigation_id: uuid.UUID, *, max_entities: int = 60
    ) -> dict[str, Any]:
        if not self.enabled:
            raise AIDisabled("ai_disabled")
        context, valid_ids = await self._build_context(investigation_id, max_entities)
        raw = await self._complete(json.dumps(context, default=str))
        parsed = _parse_json(raw)

        claims: list[AIClaim] = []
        for item in parsed.get("claims", []):
            ids = [
                uuid.UUID(str(i))
                for i in item.get("evidence_ids", [])
                if _is_uuid(str(i)) and uuid.UUID(str(i)) in valid_ids
            ]
            if not ids:
                continue  # ungrounded claim: dropped, never shown
            claims.append(
                AIClaim(
                    statement=str(item.get("statement", ""))[:1000],
                    evidence_ids=ids,
                    confidence=max(0.0, min(1.0, float(item.get("confidence", 0.5)))),
                )
            )

        return {
            "summary": str(parsed.get("summary", ""))[:4000],
            "claims": [
                {
                    "statement": c.statement,
                    "evidence_ids": c.evidence_ids,
                    "confidence": c.confidence,
                }
                for c in claims
            ],
            "grounded": bool(claims),
            "model": self.settings.llm_model,
            "disclaimer": DISCLAIMER,
        }

    async def explain_match(self, candidate_id: uuid.UUID) -> dict[str, Any]:
        """Explain a stored correlation. The score is never recomputed by the model."""
        candidate = await self.session.get(IdentityCandidate, candidate_id)
        if candidate is None:
            raise LookupError("identity candidate not found")
        a = await self.session.get(Entity, candidate.entity_a_id)
        b = await self.session.get(Entity, candidate.entity_b_id)
        deterministic = {
            "summary": candidate.explanation,
            "claims": [
                {
                    "statement": reason.lstrip("+- ").strip(),
                    "evidence_ids": [],
                    "confidence": candidate.score,
                }
                for reason in candidate.reasons
            ],
            "grounded": True,
            "model": "deterministic",
            "disclaimer": DISCLAIMER,
        }
        if not self.enabled:
            return deterministic

        context = {
            "a": {"label": a.label if a else "", "type": a.type if a else ""},
            "b": {"label": b.label if b else "", "type": b.type if b else ""},
            "score": candidate.score,
            "band": candidate.band,
            "reasons": candidate.reasons,
            "instruction": "Explain in plain language why these reasons produce this band. "
            "Do not assert that the accounts belong to the same person.",
        }
        try:
            raw = await self._complete(json.dumps(context, default=str))
            parsed = _parse_json(raw)
            return {
                **deterministic,
                "summary": str(parsed.get("summary", candidate.explanation))[:4000],
                "model": self.settings.llm_model,
            }
        except Exception:
            return deterministic

    # -- context & transport ---------------------------------------------------

    async def _build_context(
        self, investigation_id: uuid.UUID, max_entities: int
    ) -> tuple[dict[str, Any], set[uuid.UUID]]:
        entities = list(
            (
                await self.session.execute(
                    select(Entity)
                    .where(Entity.investigation_id == investigation_id)
                    .order_by(Entity.confidence.desc())
                    .limit(max_entities)
                )
            ).scalars()
        )
        observations = list(
            (
                await self.session.execute(
                    select(Observation)
                    .where(Observation.investigation_id == investigation_id)
                    .order_by(Observation.observed_at.desc())
                    .limit(max_entities * 2)
                )
            ).scalars()
        )
        relationships = list(
            (
                await self.session.execute(
                    select(Relationship).where(
                        Relationship.investigation_id == investigation_id
                    )
                )
            ).scalars()
        )
        labels = {e.id: e.label for e in entities}
        context = {
            "entities": [
                {"label": e.label, "type": e.type, "confidence": e.confidence, "sources": e.sources}
                for e in entities
            ],
            "relationships": [
                {
                    "source": labels.get(r.source_entity_id, ""),
                    "target": labels.get(r.target_entity_id, ""),
                    "type": r.type,
                    "assertion": r.assertion,
                    "confidence": r.confidence,
                }
                for r in relationships[:200]
            ],
            "evidence": [
                {
                    "evidence_id": str(o.id),
                    "provider": o.provider,
                    "kind": o.kind,
                    "url": o.url,
                    "assertion": o.assertion,
                    "observed_at": o.observed_at.isoformat(),
                }
                for o in observations
            ],
        }
        return context, {o.id for o in observations}

    async def _complete(self, user_content: str) -> str:
        url = f"{self.settings.llm_base_url.rstrip('/')}/api/chat"
        payload = {
            "model": self.settings.llm_model,
            "stream": False,
            "format": "json",
            "options": {"temperature": 0.1},
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_content},
            ],
        }
        # Local by design: the investigation never leaves the host unless the operator
        # points LLM_BASE_URL somewhere else.
        async with httpx.AsyncClient(timeout=self.settings.llm_timeout_seconds) as client:
            response = await client.post(url, json=payload)
            response.raise_for_status()
            return str(response.json().get("message", {}).get("content", ""))


def _parse_json(raw: str) -> dict[str, Any]:
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if not match:
            return {}
        try:
            parsed = json.loads(match.group(0))
        except json.JSONDecodeError:
            return {}
    return parsed if isinstance(parsed, dict) else {}


def _is_uuid(value: str) -> bool:
    try:
        uuid.UUID(value)
        return True
    except ValueError:
        return False
