"""initial schema

Revision ID: 21b25c890710
Revises: 
Create Date: 2026-08-21 17:25:32.619344
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.db import GUID
from sqlalchemy.dialects import postgresql

revision: str = '21b25c890710'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('requires_api_key', sa.Boolean(), nullable=False),
    sa.Column('rpm', sa.Integer(), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Float(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('cost', sa.String(length=16), nullable=False),
    sa.Column('coverage', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_name'), ['name'], unique=True)

    op.create_table('tags',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('actor_id', GUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)

    op.create_table('investigations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('owner_id', GUID(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_investigations_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations'))
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigations_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_status'), ['status'], unique=False)

    op.create_table('entities',
    sa.Column('investigation_id', GUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=512), nullable=False),
    sa.Column('canonical_key', sa.String(length=512), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_entities_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('investigation_id', 'canonical_key', name='uq_entity_canonical')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index('ix_entity_type', ['investigation_id', 'type'], unique=False)

    op.create_table('jobs',
    sa.Column('investigation_id', GUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=24), nullable=False),
    sa.Column('target_value', sa.String(length=512), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_jobs_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index('ix_jobs_status', ['investigation_id', 'status'], unique=False)

    op.create_table('targets',
    sa.Column('investigation_id', GUID(), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('normalized', sa.String(length=512), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_targets_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_targets')),
    sa.UniqueConstraint('investigation_id', 'type', 'normalized', name='uq_target_normalized')
    )
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_targets_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_targets_normalized'), ['normalized'], unique=False)

    op.create_table('identifiers',
    sa.Column('entity_id', GUID(), nullable=False),
    sa.Column('investigation_id', GUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('normalized', sa.String(length=512), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_identifiers_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_identifiers_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identifiers')),
    sa.UniqueConstraint('entity_id', 'kind', 'normalized', name='uq_identifier_value')
    )
    with op.batch_alter_table('identifiers', schema=None) as batch_op:
        batch_op.create_index('ix_identifier_lookup', ['kind', 'normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_identifiers_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identifiers_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('identity_candidates',
    sa.Column('investigation_id', GUID(), nullable=False),
    sa.Column('entity_a_id', GUID(), nullable=False),
    sa.Column('entity_b_id', GUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_a_id'], ['entities.id'], name=op.f('fk_identity_candidates_entity_a_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_b_id'], ['entities.id'], name=op.f('fk_identity_candidates_entity_b_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_identity_candidates_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_candidates')),
    sa.UniqueConstraint('investigation_id', 'entity_a_id', 'entity_b_id', name='uq_candidate')
    )
    with op.batch_alter_table('identity_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_candidates_band'), ['band'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_candidates_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('notes',
    sa.Column('investigation_id', GUID(), nullable=False),
    sa.Column('entity_id', GUID(), nullable=True),
    sa.Column('author_id', GUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_notes_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_notes_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_notes_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('observations',
    sa.Column('investigation_id', GUID(), nullable=False),
    sa.Column('entity_id', GUID(), nullable=True),
    sa.Column('job_id', GUID(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('assertion', sa.String(length=16), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("assertion IN ('observed', 'inferred', 'correlated', 'unverified')", name=op.f('ck_observations_assertion_valid')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_observations_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_observations_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_observations_job_id_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations'))
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index('ix_obs_entity_time', ['entity_id', 'observed_at'], unique=False)
        batch_op.create_index('ix_obs_provider', ['investigation_id', 'provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('provider_runs',
    sa.Column('job_id', GUID(), nullable=False),
    sa.Column('investigation_id', GUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_provider_runs_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_provider_runs_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_runs'))
    )
    with op.batch_alter_table('provider_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_runs_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_runs_job_id'), ['job_id'], unique=False)

    op.create_table('relationships',
    sa.Column('investigation_id', GUID(), nullable=False),
    sa.Column('source_entity_id', GUID(), nullable=False),
    sa.Column('target_entity_id', GUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('assertion', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("assertion IN ('observed', 'inferred', 'correlated', 'unverified')", name=op.f('ck_relationships_assertion_valid')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_relationships_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], name=op.f('fk_relationships_source_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], name=op.f('fk_relationships_target_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationships')),
    sa.UniqueConstraint('investigation_id', 'dedupe_key', name='uq_relationship_dedupe')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index('ix_rel_source', ['source_entity_id'], unique=False)
        batch_op.create_index('ix_rel_target', ['target_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('evidence',
    sa.Column('observation_id', GUID(), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_evidence_observation_id_observations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_observation_id'), ['observation_id'], unique=False)
        batch_op.create_index('ix_evidence_sha', ['sha256'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_sha')
        batch_op.drop_index(batch_op.f('ix_evidence_observation_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_investigation_id'))
        batch_op.drop_index('ix_rel_target')
        batch_op.drop_index('ix_rel_source')

    op.drop_table('relationships')
    with op.batch_alter_table('provider_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_runs_job_id'))
        batch_op.drop_index(batch_op.f('ix_provider_runs_investigation_id'))

    op.drop_table('provider_runs')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_observations_entity_id'))
        batch_op.drop_index('ix_obs_provider')
        batch_op.drop_index('ix_obs_entity_time')

    op.drop_table('observations')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_investigation_id'))

    op.drop_table('notes')
    with op.batch_alter_table('identity_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_candidates_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_identity_candidates_band'))

    op.drop_table('identity_candidates')
    with op.batch_alter_table('identifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identifiers_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_identifiers_entity_id'))
        batch_op.drop_index('ix_identifier_lookup')

    op.drop_table('identifiers')
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_targets_normalized'))
        batch_op.drop_index(batch_op.f('ix_targets_investigation_id'))

    op.drop_table('targets')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status')
        batch_op.drop_index(batch_op.f('ix_jobs_investigation_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_type')
        batch_op.drop_index(batch_op.f('ix_entities_investigation_id'))

    op.drop_table('entities')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_status'))
        batch_op.drop_index(batch_op.f('ix_investigations_owner_id'))
        batch_op.drop_index(batch_op.f('ix_investigations_name'))

    op.drop_table('investigations')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('tags')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_name'))

    op.drop_table('sources')
    # ### end Alembic commands ###
