"""false positive risk on identity candidates

Revision ID: ca66a410fe9c
Revises: fcd91737c401
Create Date: 2026-08-22 16:31:51.836355
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

revision: str = 'ca66a410fe9c'
down_revision: str | None = 'fcd91737c401'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Adjusted from the autogenerated version: it emitted a NOT NULL column with no
    # server default, which fails on any deployment that already has candidate rows.
    # The default backfills existing rows with an empty object; they are re-populated
    # with a real assessment on the next correlation run.
    with op.batch_alter_table('identity_candidates', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'risk',
                sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                nullable=False,
                server_default=sa.text("'{}'"),
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_candidates', schema=None) as batch_op:
        batch_op.drop_column('risk')

    # ### end Alembic commands ###
