"""linked accounts for self-osint

Revision ID: fcd91737c401
Revises: 21b25c890710
Create Date: 2026-08-22 14:19:32.512151
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.db import GUID
from sqlalchemy.dialects import postgresql

revision: str = 'fcd91737c401'
down_revision: str | None = '21b25c890710'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linked_account_revocations',
    sa.Column('user_id', GUID(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('account_ref', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('remote_revocation', sa.Boolean(), nullable=False),
    sa.Column('data_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_linked_account_revocations_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_linked_account_revocations'))
    )
    with op.batch_alter_table('linked_account_revocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_linked_account_revocations_user_id'), ['user_id'], unique=False)

    op.create_table('oauth_states',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('redirect_uri', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_states')),
    sa.UniqueConstraint('state_hash', name='uq_oauth_state_hash')
    )
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.create_index('ix_oauth_state_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_states_user_id'), ['user_id'], unique=False)

    op.create_table('linked_accounts',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_account_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('account_type', sa.String(length=32), nullable=True),
    sa.Column('encrypted_token', sa.String(length=2048), nullable=True),
    sa.Column('token_state', sa.String(length=32), nullable=False),
    sa.Column('token_state_detail', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('investigation_id', GUID(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_linked_accounts_investigation_id_investigations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_linked_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_linked_accounts')),
    sa.UniqueConstraint('user_id', 'provider', name='uq_linked_account_user_provider')
    )
    with op.batch_alter_table('linked_accounts', schema=None) as batch_op:
        batch_op.create_index('ix_linked_account_user', ['user_id', 'provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_linked_accounts_token_state'), ['token_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_linked_accounts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linked_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_linked_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_linked_accounts_token_state'))
        batch_op.drop_index('ix_linked_account_user')

    op.drop_table('linked_accounts')
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_states_user_id'))
        batch_op.drop_index('ix_oauth_state_user')

    op.drop_table('oauth_states')
    with op.batch_alter_table('linked_account_revocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_linked_account_revocations_user_id'))

    op.drop_table('linked_account_revocations')
    # ### end Alembic commands ###
